baseurl: ""
url: 'https://albanyhacks.github.io'
full: false
style:
    theme: original
tracking:
    google_analytics: UA-92880122-2
social:
    twitter_handle: AlbanyHacks
seo:
    title: 'AlbanyHacks | August 9-15th'
    description: 'Hackathon based in the Capital Region'
    image: ""
organiser:
    name: Hackclub
    full_name: Hackclub
    site: 'https://hackclub.com/'
event:
    name: 'AlbanyHacks 2020'
    name_short: AlbanyHacks
    description: 'Online High School Hackathon'
    date: 'August 9-12th'
    location: 'Capital Region'
    logosrc: images/albanyhackslogo.png
    logoalt: 'AlbanyHacks Logo'
    trust_badge:
        year: '2020'
        region: eu
        color: blue
        links:
            - {text: Sponsor, href: 'mailto:johnyin596@gmail.com'}
    about:
        description: "AlbanyHacks is an online hackathon coming to the Capital Region this August.{::nomarkdown}<br />{:/} It'll bring together students for three fun days of invention, coding, and learning.{::nomarkdown}<br />{:/} Brought to you by [Hack Club](https://hackclub.com/).\n"
    workshops:
        name: N/A
    sponsors:
        tier2:
            - {logo: images/particle__logo.png, name: Particle, url: 'https://www.particle.io/'}
            - {logo: images/GF_Logo_highres_300dpi.jpg, name: 'Global Foundries', url: 'https://www.globalfoundries.com/'}
            - {logo: images/balsamiq-logo-screen.png, name: 'Balsamiq', url: 'https://balsamiq.com/'}
    info:
        sections:
            - {image: images/header1.png, imagealt: 'Circuitry on a breadboard', title: 'Student Oriented', description: "We are the one of the few student run hackathons in the Capital Region focused specifically for high school students.\n"}
            - {image: images/header2.png, imagealt: 'Mentor assiting workshop attendees', title: Workshops, description: "We will also be having beginner-friendly workshops parallel to the main event. Watch this space!\n"}
            - {image: images/header3.png, imagealt: 'Two mentors discussing information on a computer', title: Mentors, description: "We will have mentors available on site to guide you along the way!\n"}
    faq:
        -
            question: 'What is a hackathon?'
            answer: "A hackathon is an invention marathon. Students come together to build cool software & hardware hacks over 12-24 hours. They're [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).\n"
        -
            question: 'How much does it cost?'
            answer: "Nothing. Attending a hackathon is free.\n"
        -
            question: 'I''m a complete beginner. Can I still come?'
            answer: "Absolutely! We especially encourage people that are new in the field to come along as a hackathon is a great place to get started. [Drop us a message](mailto:johnyin596@gmail.com) if you have any concerns.\n"
        -
            question: 'Where is the event?'
            answer: "We are online now. Going to post the devpost link soon!\n"
        -
            question: 'How big are the teams?'
            answer: "Teams are no bigger than 4 people.\n"
        -
            question: 'What are the prizes?'
            answer: "We will have prizes worth $150 in value! If you do not live in the United States, then we cannot ship you a prize.\n"
        -
            question: 'Is there a code of conduct?'
            answer: 'We will be using the MLH code of conduct and will be enforcing it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).'
schedule:
    Saturday:
        -
            text: 'Start of registration'
            start: '10:00'
            track: main
        -
            text: 'Team forming session 1'
            start: '10:30'
            end: '11:00'
            track: main
        -
            text: 'Opening ceremony'
            start: '11.00'
            end: '12:00'
            track: main
        -
            text: 'Start hacking'
            start: '12:00'
            track: main
        -
            text: 'Team forming session 2'
            start: '12:01'
            end: '12:30'
            track: main
        -
            text: 'Introduction to electronics workshop'
            start: '12:00'
            end: '13:00'
            track: ws
        -
            text: 'Introduction to MiRo workshop'
            start: '12.00'
            end: '13.00'
            track: ws
        -
            text: Lunch
            start: '13:00'
            end: '14:00'
            track: main
        -
            text: 'Introduction to Microbit workshop'
            start: '14:00'
            end: '15:00'
            track: ws
        -
            text: 'GitHub workshop'
            start: '15.00'
            end: '16.00'
            track: ws
        -
            text: 'Line follower workshop'
            start: '15:30'
            end: '17.00'
            track: ws
        -
            text: 'FPGA workshop'
            start: '17:00'
            end: '18:00'
            track: ws
        -
            text: Dinner
            start: '18:00'
            end: '19:00'
            track: main
        -
            text: 'Introduction to IoT workshop'
            start: '19.00'
            end: '20.00'
            track: ws
    Sunday:
        -
            text: 'Midnight snack'
            start: '00:00'
        -
            text: Breakfast
            start: '08:00'
            end: '09:00'
        -
            text: 'Submissions due'
            start: '12:00'
        -
            text: Lunch
            start: '12.00'
            end: '13.00'
        -
            text: Demos
            start: '13:30'
            end: '15:00'
        -
            text: 'Closing ceremony'
            start: '15:30'
            end: '16:30'
    register:
        message: "Thanks for signing up! {::nomarkdown}<br />{:/} You'll receive more information closer to the hackathon.\n"
markdown: kramdown
exclude:
    - node_modules
    - gulpfile.js
    - Gemfile
    - Gemfile.lock
    - package.json
    - README.md
    - CNAME
