baseurl: ""
url: 'https://albanyhacks.github.io'
full: false
style:
    theme: original
tracking:
    google_analytics: UA-92880122-2
social:
    twitter_handle: AlbanyHacks
seo:
    title: 'AlbanyHacks | 4th March 2020'
    description: '24-hour hackathon in Capital Region'
    image: ''
organiser:
    name: 'Shaker Coding Club and Hackclub'
    full_name: Hackclub
    site: 'https://hackclub.com/'
event:
    name: 'AlbanyHacks 2020'
    name_short: AlbanyHacks
    description: '24-hour hackathon'
    date: '4th of April'
    location: 'Capital Region'
    logosrc: images/logo.png
    logoalt: 'AlbanyHacks Logo'
    trust_badge:
        year: '2020'
        region: eu
        color: blue
        links:
            - {text: Sponsor, href: 'mailto:johnyin596@gmail.com'}
    about:
        description: "AlbanyHacks is a 24 hour hackathon coming to the Capital Region this April.{::nomarkdown}<br />{:/} It'll bring together students for a fun weekend of invention, coding, and learning.{::nomarkdown}<br />{:/} Brought to you by Shaker Coding Club and [Hack Club](https://hackclub.com/).\n"
    workshops:
        name: N/A
    sponsors: 
        tier2:
      - logo:        "images/accenture_logo.png"
        name:        "Particle"
        url:         "https://www.particle.io/"
    info:
        sections:
            - {image: images/header1.png, imagealt: 'Circuitry on a breadboard', title: Hardware, description: "We are the one of the few student run hackathons in the Capital Region focused specifically for high school students.\n"}
            - {image: images/header2.png, imagealt: 'Mentor assiting workshop attendees', title: Workshops, description: "We will also be having beginner-friendly workshops parallel to the main event. Watch this space!\n"}
            - {image: images/header3.png, imagealt: 'Two mentors discussing information on a computer', title: Mentors, description: "We will have mentors available on site to guide you along the way!\n"}
    faq:
        -
            question: 'What is a hackathon?'
            answer: "A hackathon is an invention marathon. Students come together to build cool software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).\n"
        -
            question: 'How much does it cost?'
            answer: "Nothing. Attending a hackathon is free.\n"
        -
            question: 'I''m a complete beginner. Can I still come?'
            answer: "Absolutely! We especially encourage people that are new in the field to come along as a hackathon is a great place to get started. [Drop us a message](mailto:johnyin596@gmail.com) if you have any concerns.\n"
        -
            question: 'Where is the event?'
            answer: "TBD\n"
        -
            question: 'How big are the teams?'
            answer: "Teams are no bigger than 4 people.\n"
        -
            question: 'Do you offer travel reimbursement?'
            answer: "We cannot reimburse you for your travel expenses.\n"
        -
            question: 'Is there a code of conduct?'
            answer: 'We will be using the MLH code of conduct and will be enforcing it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).'
    schedule:
        Saturday:
            start: '10:00'
            track: main
            text: 'To Be Determined'
            end: '11:00'
    register:
        message: "Thanks for signing up! {::nomarkdown}<br />{:/} You'll receive more information closer to the hackathon.\n"
markdown: kramdown
exclude:
    - node_modules
    - gulpfile.js
    - Gemfile
    - Gemfile.lock
    - package.json
    - README.md
    - CNAME
